name: React App Deploy to Surge

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
    
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
        
    - name: Build React App
      run: sudo yarn build
      
    - name: Install Surge
      run: npm install --global surge

    - name: Deploy to Surge
      run: surge ./build shopping-cart-redux-toolkit.surge.sh --token ${{ secrets.SURGE_TOKEN }}
